from data import make_noised, make_noised_mean_cov, make_noised_mean
import torch 
import torch.optim as optim
import torch.nn.functional as F

import numpy as np
import os
import argparse
from twolayer import TwoLayer, NLayer
from joblib import Parallel, delayed
import pickle
import os

NUM_TEST = 100000

def loss(dat,z,network): 
    """Computes the MSE loss of the network on a batch of data."""
    out = network(dat)
    return F.mse_loss(out, z)


def sgd_update(network, opt, t, d, bs, z_per_a, sample_first_dim=np.sign): 
    """Performs one SGD update step on the network using a batch of data generated by make_noised."""
    dat,z = make_noised(d, bs, npoints_z_over_a=z_per_a, t=t, sample_first_dim=sample_first_dim)
    loss_ = loss(dat, z, network)
    network.zero_grad()  # reset the gradients before the backward pass
    loss_.backward()  # backward pass
    opt.step() 

    return network


def get_network(m, d, act=F.tanh, wnorm=1,N=2, skip=0): 
    """Returns a network instance based on the specified architecture."""
    if N==2:
        network = TwoLayer(d,m,act=act, wnorm=wnorm)
    else: 
        network = NLayer(d,m,act=act, wnorm=wnorm, N=N,skip=skip)
    return network

def get_log_steps(nits): 
    """Generates a list of iteration steps at which to log results, spaced logarithmically."""
    log_steps = np.unique(np.logspace(0, np.log10(nits), num=30, dtype=int))
    log_steps = np.insert(log_steps, 0, 0)  # Ensure step 0 is included
    return log_steps


import inspect
import hashlib

def function_hash(func):
    """
    Returns a short hash (8 chars) from the source code of a function.
    If no source is available (e.g., builtins), returns the function name.
    """
    try:
        src = inspect.getsource(func)
    except (OSError, TypeError):
        # fallback: just use the name
        return func.__name__

    h = hashlib.sha256(src.encode()).hexdigest()
    return h[:8]

def make_filename_from_args(prefix="exp", **kwargs):
    """Constructs a filename from a set of keyword arguments, using a consistent format and hashing for functions."""
    def fmt(v):
        if isinstance(v, bool):
            return int(v)
        if callable(v):
            return function_hash(v)     # ⬅ hash used here
        if isinstance(v, (list, tuple)):
            return "-".join(map(str, v))
        return str(v)

    parts = [prefix]
    for k, v in kwargs.items():
        parts.append(f"{k}{fmt(v)}")

    return "experiments/" + "_".join(parts) + ".pkl"

def save_experiment_results(filename, results_all, **kwargs):
    """
    Save experiment results + all arguments to one file using pickle.
    
    Args:
        filename (str): Path to output file.
        results_all (dict/list): Simulation results to save.
        **kwargs: All arguments passed to learning_experiment
    """
    data = {
        "args": kwargs,
        "results": results_all
    }
    with open(filename, "wb") as f:
        pickle.dump(data, f)
    print(f"Saved results to: {filename}")



def load_experiment_by_args(directory="experiments/", prefix="exp", **kwargs):
    """
    Load a saved experiment by reconstructing its filename from hyperparameters.

    Args:
        directory (str): Where experiment_*.pkl files are stored.
        prefix (str): Prefix used in the filename constructor.
        **kwargs: Hyperparameters used in the experiment.

    Returns:
        (args_dict, results) from the .pkl file.

    Raises:
        FileNotFoundError if no matching file exists.
    """
    filename = make_filename_from_args(prefix=prefix, **kwargs)
    path = os.path.join(directory, filename)

    if not os.path.exists(path):
        raise FileNotFoundError(
            f"No experiment file found for parameters. Tried:\n  {path}"
        )

    with open(path, "rb") as f:
        data = pickle.load(f)

    return data["args"], data["results"]


def learning_experiment(
    nits, d, m, ninits, t=0.3, bs=1, npoints_z_over_a=1,
    eta=0.01, norm=False, eps=1e-8, wnorm=1, act=F.tanh,
    sample_first_dim=np.sign, Adam=False, save=True, N=2, skip=0, 
    add_cov_spike=False, correlated_latents=False
):
    """Runs the learning experiment with the specified hyperparameters and returns the results."""
    #import numpy as np
    #from joblib import Parallel, delayed

    # Create log-spaced steps
    log_steps = get_log_steps(nits)

    a_test, z_test = make_noised(d, NUM_TEST, sample_first_dim=sample_first_dim, 
                                 add_cov_spike=add_cov_spike,
                                 correlated_latents=correlated_latents)
    a_test_mean, z_test_mean = make_noised_mean(d, NUM_TEST, add_cov_spike=add_cov_spike)
    a_test_mean_cov, z_test_mean_cov = make_noised_mean_cov(d, NUM_TEST, add_cov_spike=add_cov_spike)


    def run_single_experiment(d, m, no, eta, nits, norm, wnorm,
                              track_scales=False, track_w2=False,):

        network = get_network(m, d, wnorm=wnorm, act=act, N=N, skip=skip)
        if not Adam:
            opt = optim.SGD(network.parameters(),lr=eta)
        else:
            opt = optim.Adam(network.parameters(),lr=eta)
        step_idx = 0

        results = {
            "w0": [],
            "w2_0": [],
            "w1": [],
            "wnorm": [],
            "w_2norm": [],
            "vnorm": [],
            "loss": [],
            "loss_mean": [],
            "loss_mean_cov": [],
            "v0": [],
            "v1": [],
            "u0": [], 
            "u1": [],
            "u2": [],
            "scales_mean" : [], 
            "scales_max": [], 
            "scale": []
        }

        for it in range(nits + 1):  # Include final iteration
            if it == log_steps[step_idx]:
                with torch.no_grad(): 
                    # column 0
                    col0 = network.fc1.weight[:, 0].detach()

                    # index of max overlap
                    idx = torch.argmax(torch.abs(col0)).item()

                    # max overlap value
                    w_max = torch.abs(col0[idx]).item()

                    results["w0"].append(w_max)                

                    # length (norm) of the corresponding row
                    w_len = torch.norm(network.fc1.weight[idx].detach(), p=2).item()
                    results["wnorm"].append(w_len)
                    results["loss"].append(loss(a_test,
                                                z_test,network).detach().item())
                    results["loss_mean"].append(loss(a_test_mean,
                                                    z_test_mean,network).detach().item())
                    results["loss_mean_cov"].append(loss(a_test_mean_cov,
                                                        z_test_mean_cov,network).detach().item())
                    results["scale"].append(network.scale.item())
                    if track_scales:
                        results["scales_mean"].append(torch.mean(torch.abs(network.scales).detach()).item())
                        results["scales_max"].append(torch.max(torch.abs(network.scales).detach()).item())

                    step_idx += 1
                    if step_idx >= len(log_steps):
                        break  # All desired steps collected

            # Only do updates if more steps remain
            if it < nits:
                sgd_update(network, opt, t=t, d=d, bs=bs, z_per_a=npoints_z_over_a, sample_first_dim=sample_first_dim)
                if norm: 
                    network.norm_transpose_weight()

        return results
    
    results_all = Parallel(n_jobs=10, verbose=1)(
            delayed(run_single_experiment)(d,m,no,eta,nits,norm, wnorm=wnorm)
            for no in range(ninits)
        )

    # Fill arrays
    if save:
        save_path = make_filename_from_args(
            nits=nits,
            d=d,
            m=m,
            ninits=ninits,
            t=t,
            bs=bs,
            npoints_z_over_a=npoints_z_over_a,
            eta=eta,
            norm=norm,
            eps=eps,
            wnorm=wnorm,
            act=act.__name__ if callable(act) else str(act),
            sample_first_dim=sample_first_dim.__name__ 
                            if callable(sample_first_dim) else str(sample_first_dim),
            Adam=Adam, 
            N=N, 
            skip=skip, 
            add_cov_spike=add_cov_spike,
            correlated_latents=correlated_latents
        )

        save_experiment_results(
            save_path,
            results_all,
            nits=nits, d=d, m=m, ninits=ninits, t=t, bs=bs,
            npoints_z_over_a=npoints_z_over_a, eta=eta, norm=norm,
            eps=eps, wnorm=wnorm, act=str(act),
            sample_first_dim=str(sample_first_dim), Adam=Adam, N=N,skip=skip
        )
        make_fig(results_all, log_steps, ninits, save_path, act, m)
    return results_all


import matplotlib.pyplot as plt
from lineardiffusion.plotting import set_nice_params

def make_fig(results_all, steps, ninits, name, act, m): 
    fig, axs = plt.subplots(1,3, figsize=(10,5))
    set_nice_params()

    axs=axs.flatten()
    for i in range(ninits):
        axs[0].plot(steps, np.array(results_all[i]["w0"])/np.array(results_all[i]["wnorm"]), color="k",)
        axs[1].plot(steps, results_all[i]["scale"], color="k")
        axs[2].plot(steps, results_all[i]["loss"], color="k", label="test loss")
        axs[2].plot(steps, results_all[i]["loss_mean"], color="r", label="loss_mean")
        axs[2].plot(steps, results_all[i]["loss_mean_cov"], color="g", label="loss_mean_cov")
        if i==0:
            axs[2].legend()

    for ax in axs:
        ax.set_xscale("log")
        ax.set_yscale("log")
        ax.set_xlabel("steps")

    axs[0].set_title(f"act={act.__name__}, m={m}")
    axs[0].set_ylabel("w overlap")
    axs[1].set_ylabel("skip connection")
    axs[2].set_ylabel("loss")

    plt.tight_layout()
    plt.savefig(f"{name}.pdf")
